sudo: required
services:
  - docker

before_install:
  - docker build -t scottfj/react-test -f ./client/Dockerfile.dev ./client


  script:
    - docker run scottfj/react-test npm test -- --coverage

  after_success:
    - docker build -t scottfj/multi-client ./client
    - docker build -t scottfj/multi-nginx ./nginx
    - docker build -t scottfj/multiserver ./server
    - docker build -t scottfj/multiworker ./worker

    # log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take thos eimages and get them pushed to docker hub now
    - docker push scottfj/multi-client
    - docker push scottfj/multi-nginx
    - docker push scottfj/multi-server
    - docker push scottfj/multi-worker




